AWSTemplateFormatVersion: "2010-09-09"
Description: Code pipeline for automated api functional testing (Using Existing IAM Role)

Parameters:
  GitHubRepositoryName:
    Type: String
  GitHubUser:
    Type: String
  GitHubBranch:
    Type: String
  GitHubToken:
    Type: String
    NoEcho: true
  BucketRoot:
    Type: String

Resources:

  CodePipelineArtifactBucket:
    DeletionPolicy: Delete
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName:
        Fn::Sub: ${AWS::StackName}-artifacts-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

  PetStoreAPISAMCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: petstore-api-stack-project
      ServiceRole: "arn:aws:iam::031342435657:role/devsecops-test-codepipelinerole"
      Artifacts:
        Type: S3
        Location: !Ref CodePipelineArtifactBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:8.11.0
      Source:
        Location: !Join ['', ['https://github.com/', !Ref GitHubUser, '/', !Ref GitHubRepositoryName]]
        Type: GITHUB
        BuildSpec: 01api/petstore-api-buildspec.yml
      TimeoutInMinutes: 10

  PostmanNewmanCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-newman-project
      ServiceRole: "arn:aws:iam::031342435657:role/devsecops-test-codepipelinerole"
      Artifacts:
        Type: S3
        Location: !Ref CodePipelineArtifactBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:2.0
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !Ref BucketRoot
      Source:
        Location: !Join ['', ['https://github.com/', !Ref GitHubUser, '/', !Ref GitHubRepositoryName]]
        Type: GITHUB
        BuildSpec: 03codebuild/postman-newman-buildspec.yml
      TimeoutInMinutes: 10

  PetStoreAPIPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: petstore-api-pipeline
      RoleArn: "arn:aws:iam::031342435657:role/devsecops-test-codepipelinerole"
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactBucket
      Stages:
      - Name: Source
        Actions:
        - Name: CheckoutPetStoreAPISource
          ActionTypeId:
            Owner: ThirdParty
            Category: Source
            Version: 1
            Provider: GitHub
          Configuration:
            Owner: !Ref GitHubUser
            Repo: !Ref GitHubRepositoryName
            Branch: !Ref GitHubBranch
            OAuthToken: !Ref GitHubToken
          OutputArtifacts:
          - Name: 'PetStoreAPI-SourceArtifact'

      - Name: Build
        Actions:
        - Name: BuildPetStoreAPI
          ActionTypeId:
            Owner: AWS
            Category: Build
            Version: 1
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref PetStoreAPISAMCodeBuildProject
          InputArtifacts:
          - Name: 'PetStoreAPI-SourceArtifact'
          OutputArtifacts:
          - Name: 'PetStoreAPI-BuildArtifact'

      - Name: Deploy
        Actions:
        - Name: GenerateChangeSet
          ActionTypeId:
            Owner: AWS
            Category: Deploy
            Version: 1
            Provider: CloudFormation
          Configuration:
            TemplatePath: 'PetStoreAPI-BuildArtifact::01api/petstore-api-output.yaml'
            ActionMode: REPLACE_ON_FAILURE 
            Capabilities: CAPABILITY_IAM
            ChangeSetName: pipeline-changeset
            RoleArn: "arn:aws:iam::031342435657:role/devsecops-test-codepipelinerole"
            StackName: petstore-api-stack
          InputArtifacts:
          - Name: 'PetStoreAPI-BuildArtifact'

        - Name: ExecuteChangeSet
          ActionTypeId:
            Owner: AWS
            Category: Deploy
            Version: 1
            Provider: CloudFormation
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            ChangeSetName: pipeline-changeset
            StackName: petstore-api-stack

      - Name: Test
        Actions:
        - Name: TestPetStoreAPI
          ActionTypeId:
            Owner: AWS
            Category: Build
            Version: 1
            Provider: CodeBuild
          Configuration:
            ProjectName: !Ref PostmanNewmanCodeBuildProject
          InputArtifacts:
            - Name: 'PetStoreAPI-SourceArtifact'
          OutputArtifacts:
            - Name: 'PetStoreAPI-TestArtifact'

            